# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: dual_arm
  joint_model_group_pose: all_zero
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
    - joint_7
    - joint_2_m
    - joint_3_m
    - joint_4_m
    - joint_5_m
    - joint_6_m
    - joint_7_m
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: mp_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7
  - name: mp_m_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint_2_m
      - joint_3_m
      - joint_4_m
      - joint_5_m
      - joint_6_m
      - joint_7_m
  - name: dual_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7
      - joint_2_m
      - joint_3_m
      - joint_4_m
      - joint_5_m
      - joint_6_m
      - joint_7_m