# Ordering from 0 to 4 is required due to real controller configuration.
topic_list:
    - name: mp_controller
      ns: dual_arm
      group: 0
      joints: ['joint_2', 'joint_3', 'joint_4', 'joint_5', 'joint_6', 'joint_7']
    - name: mp_m_controller
      ns: dual_arm
      group: 1
      joints: ['joint_2_m', 'joint_3_m', 'joint_4_m', 'joint_5_m', 'joint_6_m', 'joint_7_m']
